name: RSI Stock Monitor

on:
  schedule:
    # Ejecutar cada 30 minutos durante horario de mercado US (9:30 AM - 4:00 PM ET)
    # Convertido a UTC: 2:30 PM - 9:00 PM (horario estándar) o 1:30 PM - 8:00 PM (horario de verano)
    # Usando horario UTC más amplio para cubrir ambos casos
    - cron: '30,0 13-21 * * 1-5'  # Cada 30 min, 1:30 PM - 9:00 PM UTC, Lunes-Viernes
  
  # Permitir ejecución manual desde GitHub
  workflow_dispatch:

jobs:
  monitor-rsi:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run RSI Monitor
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python rsi_monitor.py
        
    - name: Upload logs (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: rsi-monitor-logs
        path: |
          *.log
        retention-days: 7